export const QUEUES = {
  CLOSE_DRAW: 'close-draw',
  EXECUTE_DRAW: 'execute-draw',
  STEP_GENERATE_IMAGE: 'step-generate-image',
  STEP_NOTIFY_ADMINS: 'step-notify-admins',
  STEP_PUBLISH_DRAW: 'step-publish-draw',
  STEP_PROCESS_PRIZES: 'step-process-prizes',
  STEP_CALCULATE_STATS: 'step-calculate-stats',
  SYNC_API_PLANNING: 'sync-api-planning',
  SYNC_API_TICKETS: 'sync-api-tickets',
  SYNC_SCRAPE_TICKETS: 'sync-scrape-tickets',
  SIMULATE_BETS: 'simulate-bets',
  TEST_BETS: 'test-bets',
  GENERATE_DAILY_DRAWS: 'generate-daily-draws',
  PIRAMIDE_LOTOANIMALITO: 'piramide-lotoanimalito',
  RESUMEN_LOTOANIMALITO: 'resumen-lotoanimalito',
  PIRAMIDE_LOTTOPANTERA: 'piramide-lottopantera',
  RESUMEN_LOTTOPANTERA: 'resumen-lottopantera',
  RECOMENDACIONES_TRIPLE: 'recomendaciones-triple',
  RESUMEN_TRIPLE: 'resumen-triple',
  RETRY_FAILED_PUBLICATIONS: 'retry-failed-publications',
  CLEANUP_LOGS: 'cleanup-logs',
};

export const QUEUE_CONFIGS = {
  [QUEUES.CLOSE_DRAW]: {
    retryLimit: 5,
    retryDelay: 5,
    retryBackoff: true,
    expireInMinutes: 5,
  },
  [QUEUES.EXECUTE_DRAW]: {
    retryLimit: 3,
    retryDelay: 5,
    retryBackoff: true,
    expireInMinutes: 2,
  },
  [QUEUES.STEP_GENERATE_IMAGE]: {
    retryLimit: 4,
    retryDelay: 3,
    retryBackoff: true,
    expireInMinutes: 3,
  },
  [QUEUES.STEP_NOTIFY_ADMINS]: {
    retryLimit: 3,
    retryDelay: 5,
    retryBackoff: true,
    expireInMinutes: 2,
  },
  [QUEUES.STEP_PUBLISH_DRAW]: {
    retryLimit: 4,
    retryDelay: 5,
    retryBackoff: true,
    expireInMinutes: 5,
  },
  [QUEUES.STEP_PROCESS_PRIZES]: {
    retryLimit: 5,
    retryDelay: 10,
    retryBackoff: true,
    expireInMinutes: 10,
  },
  [QUEUES.STEP_CALCULATE_STATS]: {
    retryLimit: 3,
    retryDelay: 5,
    retryBackoff: true,
    expireInMinutes: 2,
  },
  [QUEUES.SYNC_API_PLANNING]: {
    retryLimit: 3,
    retryDelay: 5,
    retryBackoff: true,
    expireInMinutes: 3,
  },
  [QUEUES.SYNC_API_TICKETS]: {
    retryLimit: 3,
    retryDelay: 5,
    retryBackoff: true,
    expireInMinutes: 2,
  },
  [QUEUES.SYNC_SCRAPE_TICKETS]: {
    // Scraping handles its own internal retry (1 reintento extra) — pg-boss-level retry
    // is kept low to avoid spamming the sidecar when Maxplay is down.
    retryLimit: 1,
    retryDelay: 30,
    retryBackoff: false,
    expireInMinutes: 3,
  },
  [QUEUES.SIMULATE_BETS]: {
    retryLimit: 2,
    retryDelay: 3,
    retryBackoff: true,
    expireInMinutes: 1,
  },
  [QUEUES.TEST_BETS]: {
    retryLimit: 2,
    retryDelay: 3,
    retryBackoff: true,
    expireInMinutes: 1,
  },
  [QUEUES.GENERATE_DAILY_DRAWS]: {
    retryLimit: 3,
    retryDelay: 5,
    retryBackoff: true,
    expireInMinutes: 5,
  },
  [QUEUES.PIRAMIDE_LOTOANIMALITO]: {
    retryLimit: 3,
    retryDelay: 5,
    retryBackoff: true,
    expireInMinutes: 3,
  },
  [QUEUES.RESUMEN_LOTOANIMALITO]: {
    retryLimit: 3,
    retryDelay: 5,
    retryBackoff: true,
    expireInMinutes: 3,
  },
  [QUEUES.PIRAMIDE_LOTTOPANTERA]: {
    retryLimit: 3,
    retryDelay: 5,
    retryBackoff: true,
    expireInMinutes: 3,
  },
  [QUEUES.RESUMEN_LOTTOPANTERA]: {
    retryLimit: 3,
    retryDelay: 5,
    retryBackoff: true,
    expireInMinutes: 3,
  },
  [QUEUES.RECOMENDACIONES_TRIPLE]: {
    retryLimit: 3,
    retryDelay: 5,
    retryBackoff: true,
    expireInMinutes: 3,
  },
  [QUEUES.RESUMEN_TRIPLE]: {
    retryLimit: 3,
    retryDelay: 5,
    retryBackoff: true,
    expireInMinutes: 3,
  },
  [QUEUES.RETRY_FAILED_PUBLICATIONS]: {
    retryLimit: 2,
    retryDelay: 10,
    retryBackoff: true,
    expireInMinutes: 5,
  },
};
